### ISSUE TITLE
JarvisAi error

### ISSUE THREAD

**Issue by AmrutRaote** [Dipeshpal/Jarvis-Assisant#10]
Traceback (most recent call last):
  File "E:\python\pythonProject\script\main.py", line 14, in <module>
    status, command = obj.hot_word_detect()
AttributeError: 'JarvisAssistant' object has no attribute 'hot_word_detect'

**Comment by Dipeshpal** [comment]
Install latest version of JarvisAI

**Comment by ghost** [comment]
> Install latest version of JarvisAI

how to know I I have latest version
