### ISSUE TITLE
how to solve this problem

### ISSUE THREAD

**Issue by Chinesee** [Dipeshpal/Jarvis-Assisant#16]
FileNotFoundError: The path does not exist.
[ WARN:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-m8us58q4\opencv\modules\videoio\src\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback

**Comment by Dipeshpal** [comment]
library issues opencv
