### ISSUE TITLE
error pls help fast

### ISSUE THREAD

**Issue by ghost** [Dipeshpal/Jarvis-Assisant#19]
C:\Users\Admin\PycharmProjects\pythonProject1\venv\Scripts\python.exe C:/Users/Admin/PycharmProjects/pythonProject1/main.py
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\pythonProject1\main.py", line 11, in <module>
    obj = JarvisAI.JarvisAssistant(sync=True, token='5ec64be7ff718ac25917c198f3d7a4', disable_msg=False,
TypeError: JarvisAssistant.__init__() got an unexpected keyword argument 'sync'

**Comment by Dipeshpal** [comment]
update JarvisAI

**Comment by ghost** [comment]
Thanx a lot man
